on:
  schedule:
    - cron: "00 12 * * 5"
  workflow_dispatch: 

name: download DLRG assets
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: checkout correct branch
      run: |
        git checkout -B update/assets
        git fetch -p

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: install dependencies
      run: npm install -g tsx

    - name: download assets
      run: npx tsx scripts/download_assets.ts

    - name: check if there are uncommitted changes
      shell: bash
      id: changes
      run: |
        clean=$(git status | grep "nothing to commit (working directory clean)")
        if [ -z "$clean" ]; then a="false"; else a="true"; fi
        echo "CLEAN=$a" >> $GITHUB_OUTPUT

    - name: Create/Update Pull Request
      uses: peter-evans/create-pull-request@v6
      if: ${{ steps.changes.outputs.CLEAN  == 'false' }}
      with:
        add-paths: public/dlrg-assets
        branch: update/assets
        assignees: tristankechlo
        title: "[Update] Update der DLRG-Assets"
        body: "Die Assets von `api.dlrg.net` und `dlrg.de` wurden aktualisiert."
        commit-message: "update assets"
        author: tristankechlo <66692834+tristankechlo@users.noreply.github.com>
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
