on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

name: lint
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Get version from package.json
      id: props
      shell: bash
      run: echo "PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: modules-${{ steps.props.outputs.PACKAGE_VERSION }}-${{ hashFiles('package.json') }}

    - name: npm install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: EsLint
      run: npm run lint
